// Code generated by protoc-gen-go.
// source: baggage.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	baggage.proto

It has these top-level messages:
	BaggageMessage
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type BaggageMessage struct {
	Namespace        []*BaggageMessage_NamespaceData `protobuf:"bytes,1,rep,name=namespace" json:"namespace,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *BaggageMessage) Reset()                    { *m = BaggageMessage{} }
func (m *BaggageMessage) String() string            { return proto1.CompactTextString(m) }
func (*BaggageMessage) ProtoMessage()               {}
func (*BaggageMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BaggageMessage) GetNamespace() []*BaggageMessage_NamespaceData {
	if m != nil {
		return m.Namespace
	}
	return nil
}

// Mapping of key to several values
type BaggageMessage_BagData struct {
	Key              []byte   `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            [][]byte `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BaggageMessage_BagData) Reset()                    { *m = BaggageMessage_BagData{} }
func (m *BaggageMessage_BagData) String() string            { return proto1.CompactTextString(m) }
func (*BaggageMessage_BagData) ProtoMessage()               {}
func (*BaggageMessage_BagData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *BaggageMessage_BagData) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *BaggageMessage_BagData) GetValue() [][]byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// Mapping of a namespace to a BagData
type BaggageMessage_NamespaceData struct {
	Key              []byte                    `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Bag              []*BaggageMessage_BagData `protobuf:"bytes,2,rep,name=bag" json:"bag,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *BaggageMessage_NamespaceData) Reset()                    { *m = BaggageMessage_NamespaceData{} }
func (m *BaggageMessage_NamespaceData) String() string            { return proto1.CompactTextString(m) }
func (*BaggageMessage_NamespaceData) ProtoMessage()               {}
func (*BaggageMessage_NamespaceData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *BaggageMessage_NamespaceData) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *BaggageMessage_NamespaceData) GetBag() []*BaggageMessage_BagData {
	if m != nil {
		return m.Bag
	}
	return nil
}

func init() {
	proto1.RegisterType((*BaggageMessage)(nil), "proto.BaggageMessage")
	proto1.RegisterType((*BaggageMessage_BagData)(nil), "proto.BaggageMessage.BagData")
	proto1.RegisterType((*BaggageMessage_NamespaceData)(nil), "proto.BaggageMessage.NamespaceData")
}

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4a, 0x4c, 0x4f,
	0x4f, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x3b, 0x19,
	0xb9, 0xf8, 0x9c, 0x20, 0x12, 0xbe, 0xa9, 0xc5, 0xc5, 0x40, 0x4a, 0xc8, 0x8c, 0x8b, 0x33, 0x2f,
	0x31, 0x37, 0xb5, 0xb8, 0x20, 0x31, 0x39, 0x55, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x19,
	0xa2, 0x49, 0x0f, 0x55, 0xa5, 0x9e, 0x1f, 0x4c, 0x99, 0x4b, 0x62, 0x49, 0xa2, 0x94, 0x2a, 0x17,
	0x3b, 0x50, 0x1e, 0xc4, 0x14, 0xe2, 0xe6, 0x62, 0xce, 0x4e, 0xad, 0x04, 0x6a, 0x66, 0xd2, 0xe0,
	0x11, 0xe2, 0xe5, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x9a, 0xc5, 0x23, 0xe5,
	0xc1, 0xc5, 0x8b, 0xa2, 0x0f, 0x55, 0xb1, 0x16, 0x17, 0x33, 0xd0, 0x9d, 0x60, 0xa5, 0xdc, 0x46,
	0xb2, 0xd8, 0xad, 0x85, 0xda, 0x02, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x45, 0x4a, 0x7c, 0xd2,
	0x00, 0x00, 0x00,
}
