// Code generated by protoc-gen-go.
// source: op.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	op.proto

It has these top-level messages:
	Int
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	xtgrpc "github.com/brownsys/tracing-framework-go/xtrace/grpc"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Int struct {
	Num int64 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
}

func (m *Int) Reset()                    { *m = Int{} }
func (m *Int) String() string            { return proto.CompactTextString(m) }
func (*Int) ProtoMessage()               {}
func (*Int) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Int)(nil), "main.Int")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Operator service

type OperatorClient interface {
	PerformOp(ctx context.Context, in *Int, opts ...grpc.CallOption) (*Int, error)
}

type operatorClient struct {
	cc *grpc.ClientConn
}

func NewOperatorClient(cc *grpc.ClientConn) OperatorClient {
	return &operatorClient{cc}
}

func (c *operatorClient) PerformOp(ctx context.Context, in *Int, opts ...grpc.CallOption) (*Int, error) {
	out := new(Int)
	err := xtgrpc.Invoke(ctx, "/main.Operator/PerformOp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Operator service

type OperatorServer interface {
	PerformOp(context.Context, *Int) (*Int, error)
}

func RegisterOperatorServer(s *grpc.Server, srv OperatorServer) {
	s.RegisterService(&_Operator_serviceDesc, srv)
}

func _Operator_PerformOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).PerformOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Operator/PerformOp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).PerformOp(ctx, req.(*Int))
	}
	return interceptor(ctx, in, info, handler)
}

var _Operator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Operator",
	HandlerType: (*OperatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PerformOp",
			Handler:    _Operator_PerformOp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("op.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0x2f, 0xd0, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x12, 0xe7, 0x62, 0xf6, 0xcc,
	0x2b, 0x11, 0x12, 0xe0, 0x62, 0xce, 0x2b, 0xcd, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x02,
	0x31, 0x8d, 0xf4, 0xb9, 0x38, 0xfc, 0x0b, 0x52, 0x8b, 0x12, 0x4b, 0xf2, 0x8b, 0x84, 0x94, 0xb9,
	0x38, 0x03, 0x52, 0x8b, 0xd2, 0xf2, 0x8b, 0x72, 0xfd, 0x0b, 0x84, 0x38, 0xf5, 0x40, 0x1a, 0xf5,
	0x3c, 0xf3, 0x4a, 0xa4, 0x10, 0x4c, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xb1, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x95, 0xd5, 0xbb, 0xcd, 0x62, 0x00, 0x00, 0x00,
}
